### ISSUE TITLE
Test case involving imports

### ISSUE THREAD

**Issue by tjohnson-z142** [practicalswift/swift-compiler-crashes#110]
Can you take a test case involving imported headers from Obj-C (via module map or bridging header)?

**Comment by practicalswift** [comment]
@tjohnson-z142 Perhaps so! :-)  Could you post a GitHub gist showing the problem?

**Comment by tjohnson-z142** [comment]
Well, actually, the headers in question are under copyright, so we would either need to alter the license of the project slightly or build a "generic" version.

Project: https://expirebox.com/download/71be8b3a5a08e3b4de8f730f4680d80c.html

Delete link: https://expirebox.com/delete/704df17495bb8f63d50d8d385dfaba3b.html

Here's a link expiring in 48 hours if you want to check it out.

**Comment by tjohnson-z142** [comment]
@practicalswift How is this code? Put it in a bridging header include and I'm told that it will fail. Haven't loaded it up myself, but I believe it.

The assertion is that templating 3+ levels deep crashes the compiler.

@interface A<T> : NSObject
@end

@interface B<T> : A<T>
@end

@interface C : B<C*>
@end

**Comment by tjohnson-z142** [comment]
Actually, I'll close this. They can send you the Xcode project if they want. Maybe already have.
