### ISSUE TITLE
How about compiler hangs?

### ISSUE THREAD

**Issue by adfernandes** [practicalswift/swift-compiler-crashes#53]
So, I have a nice short test case that produces a l-o-n-g compiler hang... but it doesn't crash.

I actually don't know how long it takes to compile; it's only a few short lines, but I've never let it go longer 
than an hour...

The bug is due to type inference for long nested arrays.

[GolaySequences~Compiles~Slowly.swift](https://gist.github.com/adfernandes/aee8ce0fc65b8adef4ac)

If you add explicit type annotations, it works as expected [GolaySequences~Compiles~Quickly.swift](https://gist.github.com/adfernandes/50414650cb94cfc25f12).

The bug was reported to Apple on 21 June 2014 as rdar://problem/17409056.

My question: since this is a hang, and this repo appears to be going through automagic crash-validation... how do you want this reported or added? (Or do you?)

Thanks for putting this together!

**Comment by beltex** [comment]
Definitely send in a PR! Just suffix the filename with `timeout.swift`, which will tell the test suite runner that this is a compiler hang bug. It will attempt to compile it with a [5 second timeout](https://github.com/practicalswift/swift-compiler-crashes/blob/master/test.sh#L135-137).

**Comment by practicalswift** [comment]
Yes, @beltex is absolutely right! :-) @adfernandes, welcome as a contributor – I'm closing this issue for now and looking forward to your PR :-)
