### ISSUE TITLE
Can't find function for crash

### ISSUE THREAD

**Issue by champo** [practicalswift/swift-compiler-crashes#55]
I've found a crash a while ago and I just found about this repo. Thought I contribute, so I went through the steps in the guidelines. Turns out, the bash line to get the name of the function that crashes gives me an empty output. So, I'm not sure if the crash doesn't belong here or if I'm doing something wrong.

The code is:

```swift
class Err {}

class APIObject {}

enum APIResult<T : AnyObject> {
    case Error(Err)
    case Value(T)
}


func thisBreaksCompilation(res : APIResult<APIObject>) {
    
    switch (res) {
    case .Value(let res):
        println("Value! \(res)")
    case .Error(let err):
        println("erro")
    }
    
}

thisBreaksCompilation(APIResult.Value(APIObject()))
```

The compiler output is:
```
PHI node operands are not the same type as the result!
  %12 = phi %C4main9APIObject* [ %8, %7 ]
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by practicalswift** [comment]
@champo The crash belongs here :-)  Ignore the bash line to get the name (it doesn't work for this type of crash), just go with "phi-node-operands-are-not-the-same-type" or something along that line :-)

I'll update the contribution guidelines!
