### ISSUE TITLE
Cannot find a page with some graphs how the quality of swift compiler evolves

### ISSUE THREAD

**Issue by juangamnik** [practicalswift/swift-compiler-crashes#69]
It would be nice to see on some charts/graphs how many new compiler problems arise and how many are fixed with each release as well as how many of the tests currently crash. I couldn't find such information. Perhaps the Readme.md is the right place? Or the wiki?

**Comment by practicalswift** [comment]
@juangamnik I've thought about that too. Any programmatically generated graph contributions would be of great interest :-)

**Comment by tengyifei** [comment]
<div>
    <a href="https://plot.ly/~tengyifei/19/" target="_blank" title="Swift Compiler Crashes" style="display: block; text-align: center;"><img src="https://plot.ly/~tengyifei/19.png" alt="Swift Compiler Crashes" style="max-width: 100%;width: 1151px;"  width="1151" onerror="this.onerror=null;this.src='https://plot.ly/404.png';" /></a>
    <script data-plotly="tengyifei:19"  src="https://plot.ly/embed.js" async></script>
</div>

https://plot.ly/~tengyifei/19/swift-compiler-crashes/

Code: https://github.com/tengyifei/swift-crash-visualizer

**Comment by practicalswift** [comment]
@tengyifei Wow! Thank you!

If you have time, could you please also post a graph covering only the period from October 1:st 2015 and onwards? The dupe identification code was improved on September 27:th (see commit 7be0d1b48a3a531c15866c1a84e6160b1470c8bf), so before that date there were a lot of dupes.

Again - thank you a lot! :-)

**Comment by tengyifei** [comment]
No problem. Check this out:

<div>
    <a href="https://plot.ly/~tengyifei/26/" target="_blank" title="Crashes vs Fixed" style="display: block; text-align: center;"><img src="https://plot.ly/~tengyifei/26.png" alt="Crashes vs Fixed" style="max-width: 100%;width: 1151px;"  width="1151" onerror="this.onerror=null;this.src='https://plot.ly/404.png';" /></a>
    <script data-plotly="tengyifei:26"  src="https://plot.ly/embed.js" async></script>
</div>

https://plot.ly/~tengyifei/26/crashes-vs-fixed/
